mysql:
  user: root
  password: root
  host: 127.0.0.1
  port: 3306
  dbname: gobloger
  charset: utf8
  parse_time: true
  loc: Local
redis:
    host: 192.168.1.1
    port: 1234
    auth: 123456
app:
  name: goblog